apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.monoptic.io 
spec:
  group: monoptic.io
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    singular: database
    shortNames:
    - db
    - dbs
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Database metadata.
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: Database spec.
              type: object
              properties:
                url:
                  description: JDBC connection URL
                  type: string
                secret:
                  description: Secret containing username, password, etc.
                  type: string
              required:
              - url
            status:
              type: object
              properties: 
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: URL
        type: string
        description: JDBC URL.
        jsonPath: .spec.url
