/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.monoptic.kubernetes.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1ViewStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-15T21:48:13.764Z[Etc/UTC]")
public class V1alpha1ViewStatus {
  public static final String SERIALIZED_NAME_MATERIALIZED_TIMESTAMP = "materializedTimestamp";
  @SerializedName(SERIALIZED_NAME_MATERIALIZED_TIMESTAMP)
  private String materializedTimestamp;

  public static final String SERIALIZED_NAME_MATERIALIZED_VIEW = "materializedView";
  @SerializedName(SERIALIZED_NAME_MATERIALIZED_VIEW)
  private String materializedView;


  public V1alpha1ViewStatus materializedTimestamp(String materializedTimestamp) {
    
    this.materializedTimestamp = materializedTimestamp;
    return this;
  }

   /**
   * Indicates freshness of a materialized view.
   * @return materializedTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates freshness of a materialized view.")

  public String getMaterializedTimestamp() {
    return materializedTimestamp;
  }


  public void setMaterializedTimestamp(String materializedTimestamp) {
    this.materializedTimestamp = materializedTimestamp;
  }


  public V1alpha1ViewStatus materializedView(String materializedView) {
    
    this.materializedView = materializedView;
    return this;
  }

   /**
   * The materialized version of .spec.sql.
   * @return materializedView
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The materialized version of .spec.sql.")

  public String getMaterializedView() {
    return materializedView;
  }


  public void setMaterializedView(String materializedView) {
    this.materializedView = materializedView;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1ViewStatus v1alpha1ViewStatus = (V1alpha1ViewStatus) o;
    return Objects.equals(this.materializedTimestamp, v1alpha1ViewStatus.materializedTimestamp) &&
        Objects.equals(this.materializedView, v1alpha1ViewStatus.materializedView);
  }

  @Override
  public int hashCode() {
    return Objects.hash(materializedTimestamp, materializedView);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1ViewStatus {\n");
    sb.append("    materializedTimestamp: ").append(toIndentedString(materializedTimestamp)).append("\n");
    sb.append("    materializedView: ").append(toIndentedString(materializedView)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

